source 'https://Jasperav@bitbucket.org/Jasperav/specs.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!
target 'JVGenericTableView_Tests' do
  pod 'JVGenericTableView', :path => '../'
  
  
end
